/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Shared site tokens and the existing admin inventory palette.
        brand: {
          navy: '#1b2b52',
          patriot: '#b22234',
          steel: '#707070',
        },
        admin: {
          ink: '#263854',
          muted: '#60708a',
          subtle: '#506584',
          faint: '#75839a',
          sort: '#7b8ca8',
          disabled: '#9aa6b8',
          link: '#31518b',
          'link-hover': '#355280',
          panel: '#ffffff',
          'panel-count': '#dce5f5',
          'panel-muted': '#f7f9fd',
          'panel-soft': '#fbfcff',
          'panel-selected': '#f2f6ff',
          'panel-tab': '#eaf0fa',
          border: '#dce3ef',
          'border-strong': '#ccd7ea',
          'border-subtle': '#e7ecf4',
          'border-model-action': '#edf0f6',
          'border-tag': '#dce5f3',
          success: '#21764e',
          'success-soft': '#e8f6ef',
          warning: '#9b6417',
          'warning-strong': '#8a5711',
          'warning-border': '#d8a741',
          'warning-soft': '#fff4dc',
          focus: '#8fa7d1',
          repair: '#ab571d',
          'repair-soft': '#fff0e6',
          'repair-rail': '#c46b25',
          'status-available': '#2f8f62',
          'status-reserved': '#b4771b',
          'status-inactive': '#8994a7',
          marker: '#edf2fb',
          'danger-tag': '#f9dde1',
          eyebrow: '#b21f36',
          notice: '#166534',
          'notice-soft': '#eef8f1',
          used: '#7051a0',
          danger: '#a51f34',
          'danger-soft': '#fff2f3',
          'danger-subtle': '#fff9fa',
          'danger-border': '#ecc7cd',
          'primary-from': '#31518b',
          'primary-to': '#1b2b52',
          neutral: '#667288',
          'neutral-soft': '#eef0f4',
        },
      },
      fontFamily: {
        primary: ['var(--font-primary)'],
        secondary: ['var(--font-secondary)'],
        logo: ['var(--font-logo)'],
      },
      screens: {
        // Matches the smallest and tablet breakpoints already used by scoped CSS.
        xs: '360px',
        tablet: '900px',
      },
      borderRadius: {
        control: '0.55rem',
        button: '0.6rem',
        toolbar: '0.8rem',
        panel: '0.85rem',
      },
      minHeight: {
        control: '2.7rem',
      },
      height: {
        control: '2.7rem',
        'control-sm': '2.25rem',
      },
      spacing: {
        'control-inline': '0.75rem',
        'control-block': '0.6rem',
        'filter-inline': '0.7rem',
        'filter-block': '0.55rem',
        'button-inline': '1rem',
        'button-block': '0.65rem',
      },
      boxShadow: {
        panel: '0 0.75rem 2rem rgba(25, 42, 78, 0.06)',
        card: '0 0.65rem 1.5rem rgba(25, 42, 78, 0.05)',
        toolbar: '0 0.65rem 1.5rem rgba(25, 42, 78, 0.04)',
        raised: '0 0.9rem 2rem rgba(25, 42, 78, 0.11)',
        focus: '0 0 0 0.2rem rgba(27, 43, 82, 0.1)',
        'focus-strong': '0 0 0 0.2rem rgba(49, 81, 139, 0.22)',
        'tab-active': '0 0.2rem 0.7rem rgba(25, 42, 78, 0.12)',
        button: '0 0.4rem 0.8rem rgba(25, 42, 78, 0.14)',
        'status-available': 'inset 0.2rem 0 0 #2f8f62',
        'status-reserved': 'inset 0.2rem 0 0 #b4771b',
        'status-repair': 'inset 0.2rem 0 0 #c46b25',
        'status-inactive': 'inset 0.2rem 0 0 #8994a7',
      },
      transitionDuration: {
        interaction: '180ms',
        content: '220ms',
        expand: '240ms',
      },
      transitionTimingFunction: {
        emphasized: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      backgroundImage: {
        'workspace-header': 'linear-gradient(120deg, #fff 52%, #eff4fc)',
        'model-placeholder': 'linear-gradient(145deg, #1d3264, #314d88)',
      },
    },
  },
  plugins: [],
}
