

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."contact_submissions" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text",
    "message" "text" NOT NULL,
    "status" "text" DEFAULT 'new'::"text"
);


ALTER TABLE "public"."contact_submissions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."drill_bit_models" (
    "id" bigint NOT NULL,
    "display_name" "text" NOT NULL,
    "nominal_size" "text" NOT NULL,
    "bit_type" "text" DEFAULT 'PDC'::"text" NOT NULL,
    "product_line" "text" DEFAULT ''::"text" NOT NULL,
    "iadc_code" "text" DEFAULT ''::"text" NOT NULL,
    "connection" "text" DEFAULT ''::"text" NOT NULL,
    "list_price" numeric(12,2) NOT NULL,
    "description" "text",
    "image_url" "text",
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sku" "text",
    "manufacturer_part_number" "text",
    "circulation_type" "text" DEFAULT 'standard'::"text" NOT NULL,
    "nominal_size_in" numeric(6,3),
    "connection_size_in" numeric(6,3),
    "connection_type" "text",
    "blade_count" integer,
    "cutter_count" integer,
    "body_material" "text",
    "manufacturer_specs" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    CONSTRAINT "drill_bit_models_blade_count_check" CHECK ((("blade_count" IS NULL) OR ("blade_count" > 0))),
    CONSTRAINT "drill_bit_models_circulation_type_check" CHECK (("circulation_type" = ANY (ARRAY['standard'::"text", 'reverse_circulation'::"text"]))),
    CONSTRAINT "drill_bit_models_connection_size_in_check" CHECK ((("connection_size_in" IS NULL) OR ("connection_size_in" > (0)::numeric))),
    CONSTRAINT "drill_bit_models_cutter_count_check" CHECK ((("cutter_count" IS NULL) OR ("cutter_count" > 0))),
    CONSTRAINT "drill_bit_models_list_price_check" CHECK (("list_price" >= (0)::numeric)),
    CONSTRAINT "drill_bit_models_nominal_size_in_check" CHECK ((("nominal_size_in" IS NULL) OR ("nominal_size_in" > (0)::numeric)))
);


ALTER TABLE "public"."drill_bit_models" OWNER TO "postgres";


ALTER TABLE "public"."drill_bit_models" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."drill_bit_models_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."featured_items" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "type" "text" NOT NULL,
    "media_url" "text" NOT NULL,
    "description" "text" NOT NULL,
    "order_index" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "featured_items_type_check" CHECK (("type" = ANY (ARRAY['image'::"text", 'video'::"text"])))
);


ALTER TABLE "public"."featured_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."inventory_units" (
    "id" bigint NOT NULL,
    "model_id" bigint NOT NULL,
    "asset_tag" "text",
    "status" "text" DEFAULT 'available'::"text" NOT NULL,
    "condition" "text" DEFAULT 'unknown'::"text" NOT NULL,
    "location" "text",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "inventory_units_condition_check" CHECK (("condition" = ANY (ARRAY['unknown'::"text", 'new'::"text", 'used'::"text", 'remanufactured'::"text"]))),
    CONSTRAINT "inventory_units_status_check" CHECK (("status" = ANY (ARRAY['available'::"text", 'reserved'::"text", 'in_repair'::"text", 'sold'::"text", 'scrapped'::"text"])))
);


ALTER TABLE "public"."inventory_units" OWNER TO "postgres";


ALTER TABLE "public"."inventory_units" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inventory_units_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."contact_submissions"
    ADD CONSTRAINT "contact_submissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."drill_bit_models"
    ADD CONSTRAINT "drill_bit_models_nominal_size_bit_type_product_line_iadc_co_key" UNIQUE ("nominal_size", "bit_type", "product_line", "iadc_code", "connection", "list_price");



ALTER TABLE ONLY "public"."drill_bit_models"
    ADD CONSTRAINT "drill_bit_models_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."featured_items"
    ADD CONSTRAINT "featured_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_asset_tag_key" UNIQUE ("asset_tag");



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "drill_bit_models_sku_unique_idx" ON "public"."drill_bit_models" USING "btree" ("sku") WHERE ("sku" IS NOT NULL);



CREATE INDEX "inventory_units_location_idx" ON "public"."inventory_units" USING "btree" ("location");



CREATE INDEX "inventory_units_model_id_idx" ON "public"."inventory_units" USING "btree" ("model_id");



CREATE INDEX "inventory_units_status_idx" ON "public"."inventory_units" USING "btree" ("status");



CREATE OR REPLACE TRIGGER "drill_bit_models_updated_at" BEFORE UPDATE ON "public"."drill_bit_models" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "inventory_units_updated_at" BEFORE UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "public"."drill_bit_models"("id") ON DELETE RESTRICT;



CREATE POLICY "Allow anonymous read" ON "public"."featured_items" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Allow authenticated users full access" ON "public"."featured_items" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Anyone can insert contact submissions" ON "public"."contact_submissions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Authenticated users can manage drill bit models" ON "public"."drill_bit_models" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can manage inventory units" ON "public"."inventory_units" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can update submission status" ON "public"."contact_submissions" FOR UPDATE USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Only authenticated users can view submissions" ON "public"."contact_submissions" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



ALTER TABLE "public"."contact_submissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."drill_bit_models" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."featured_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_units" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."contact_submissions" TO "anon";
GRANT ALL ON TABLE "public"."contact_submissions" TO "authenticated";
GRANT ALL ON TABLE "public"."contact_submissions" TO "service_role";



GRANT ALL ON TABLE "public"."drill_bit_models" TO "anon";
GRANT ALL ON TABLE "public"."drill_bit_models" TO "authenticated";
GRANT ALL ON TABLE "public"."drill_bit_models" TO "service_role";



GRANT ALL ON SEQUENCE "public"."drill_bit_models_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."drill_bit_models_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."drill_bit_models_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."featured_items" TO "anon";
GRANT ALL ON TABLE "public"."featured_items" TO "authenticated";
GRANT ALL ON TABLE "public"."featured_items" TO "service_role";



GRANT ALL ON TABLE "public"."inventory_units" TO "anon";
GRANT ALL ON TABLE "public"."inventory_units" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_units" TO "service_role";



GRANT ALL ON SEQUENCE "public"."inventory_units_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."inventory_units_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."inventory_units_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";
